"""Ingredient changes: food roles, essential recipe ingredients, the person's disliked foods, removed/replaced
ingredients per meal (meal_ingredient_changes), and the portions rebalanced around them.

Revision ID: 8a7f4ea34f9e
Revises: a9ed539b6f0f
Create Date: 2026-10-04 21:47:05.966641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7f4ea34f9e'
down_revision: Union[str, Sequence[str], None] = 'a9ed539b6f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_ingredient_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_plan_item_id', sa.String(length=36), nullable=False),
    sa.Column('group_id', sa.String(length=36), nullable=False),
    sa.Column('food_id', sa.String(length=60), nullable=False),
    sa.Column('replacement_food_id', sa.String(length=60), nullable=True),
    sa.Column('replacement_grams', sa.Double(), nullable=True),
    sa.Column('reason', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.String(length=6), nullable=False),
    sa.Column('added_dislike', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("reason IN ('dislike', 'unavailable')", name=op.f('ck_meal_ingredient_changes_reason_values')),
    sa.CheckConstraint("scope IN ('meal', 'always')", name=op.f('ck_meal_ingredient_changes_scope_values')),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_meal_ingredient_changes_food_id_foods')),
    sa.ForeignKeyConstraint(['meal_plan_item_id'], ['meal_plan_items.id'], name=op.f('fk_meal_ingredient_changes_meal_plan_item_id_meal_plan_items'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replacement_food_id'], ['foods.id'], name=op.f('fk_meal_ingredient_changes_replacement_food_id_foods')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_ingredient_changes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_ingredient_changes')),
    sa.UniqueConstraint('meal_plan_item_id', 'food_id', name=op.f('uq_meal_ingredient_changes_meal_plan_item_id_food_id'))
    )
    with op.batch_alter_table('meal_ingredient_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_ingredient_changes_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_ingredient_changes_meal_plan_item_id'), ['meal_plan_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_ingredient_changes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), server_default='', nullable=False))

    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_portion', sa.Double(), nullable=True))

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_notes', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disliked_foods', sa.JSON(), server_default='[]', nullable=False))


    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('essential', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_column('essential')


    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('disliked_foods')

    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_column('day_notes')

    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.drop_column('planned_portion')

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('meal_ingredient_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_ingredient_changes_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_ingredient_changes_meal_plan_item_id'))
        batch_op.drop_index(batch_op.f('ix_meal_ingredient_changes_group_id'))

    op.drop_table('meal_ingredient_changes')
    # ### end Alembic commands ###
