"""Warm-up, cool-down and cardio in the plan; exercise types; the person's own exercise swaps; cardio logs;
missing equipment in the profile.

Revision ID: a9ed539b6f0f
Revises: 8f3a1c2d4e5b
Create Date: 2026-10-04 20:29:23.986471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ed539b6f0f'
down_revision: Union[str, Sequence[str], None] = '8f3a1c2d4e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cardio_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_id', sa.String(length=60), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('minutes BETWEEN 1 AND 300', name=op.f('ck_cardio_logs_minutes_range')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_cardio_logs_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cardio_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cardio_logs')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_cardio_logs_user_id_date'))
    )
    with op.batch_alter_table('cardio_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cardio_logs_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_swaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('from_exercise_id', sa.String(length=60), nullable=False),
    sa.Column('to_exercise_id', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.String(length=10), nullable=False),
    sa.Column('scope', sa.String(length=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("reason IN ('equipment', 'busy', 'cantDo', 'pain')", name=op.f('ck_exercise_swaps_reason_values')),
    sa.CheckConstraint("scope IN ('today', 'always')", name=op.f('ck_exercise_swaps_scope_values')),
    sa.ForeignKeyConstraint(['from_exercise_id'], ['exercises.id'], name=op.f('fk_exercise_swaps_from_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['to_exercise_id'], ['exercises.id'], name=op.f('fk_exercise_swaps_to_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_swaps_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_swaps'))
    )
    with op.batch_alter_table('exercise_swaps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_swaps_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=10), server_default='strength', nullable=False))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('missing_equipment', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=5), server_default='full', nullable=False))
        batch_op.add_column(sa.Column('warmup', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('cooldown', sa.JSON(), server_default='{}', nullable=False))
        batch_op.add_column(sa.Column('reasons', sa.JSON(), server_default='[]', nullable=False))

    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_reason', sa.String(length=10), nullable=True))

    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cardio', sa.JSON(), server_default='{}', nullable=False))

    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warmup_done', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('cooldown_done', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_column('cooldown_done')
        batch_op.drop_column('warmup_done')

    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_column('cardio')

    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.drop_column('user_reason')

    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.drop_column('reasons')
        batch_op.drop_column('cooldown')
        batch_op.drop_column('warmup')
        batch_op.drop_column('kind')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('missing_equipment')

    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('exercise_swaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_swaps_user_id'))

    op.drop_table('exercise_swaps')
    with op.batch_alter_table('cardio_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cardio_logs_user_id'))

    op.drop_table('cardio_logs')
    # ### end Alembic commands ###
