"""initial schema

Revision ID: 97434f9a2435
Revises: 
Create Date: 2026-09-28 19:59:11.507986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97434f9a2435'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ar', sa.Text(), nullable=False),
    sa.Column('movement_pattern', sa.String(length=30), nullable=False),
    sa.Column('joints_loaded', sa.JSON(), nullable=False),
    sa.Column('range_of_motion', sa.String(length=12), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=12), nullable=False),
    sa.Column('primary_muscles', sa.JSON(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('muscle_names_en', sa.String(length=160), nullable=False),
    sa.Column('muscle_names_ar', sa.String(length=160), nullable=False),
    sa.Column('instructions', sa.JSON(), nullable=False),
    sa.Column('cues', sa.JSON(), nullable=False),
    sa.Column('mistakes', sa.JSON(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('image_frames', sa.JSON(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('media_source', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises'))
    )
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercises_movement_pattern'), ['movement_pattern'], unique=False)

    op.create_table('foods',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('kcal_100g', sa.Double(), nullable=False),
    sa.Column('protein_100g', sa.Double(), nullable=False),
    sa.Column('carbs_100g', sa.Double(), nullable=False),
    sa.Column('fat_100g', sa.Double(), nullable=False),
    sa.Column('fiber_100g', sa.Double(), nullable=False),
    sa.Column('units', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_foods'))
    )
    op.create_table('grocery_items',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=12), nullable=False),
    sa.Column('shelf_life', sa.String(length=8), nullable=False),
    sa.Column('buying_unit', sa.String(length=8), nullable=False),
    sa.Column('pack_size', sa.Double(), nullable=False),
    sa.Column('grams_per_unit', sa.Double(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grocery_items'))
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_ip'), ['ip'], unique=False)

    op.create_table('recipes',
    sa.Column('id', sa.String(length=60), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False),
    sa.Column('prep_min', sa.Integer(), nullable=False),
    sa.Column('cook_min', sa.Integer(), nullable=False),
    sa.Column('fridge_days', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('storage_en', sa.Text(), nullable=False),
    sa.Column('storage_ar', sa.Text(), nullable=False),
    sa.Column('reheating_en', sa.Text(), nullable=False),
    sa.Column('reheating_ar', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=2), nullable=False),
    sa.Column('theme', sa.String(length=6), nullable=False),
    sa.Column('adult_confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('checkins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('weight_kg', sa.Double(), nullable=True),
    sa.Column('waist_cm', sa.Double(), nullable=True),
    sa.Column('hips_cm', sa.Double(), nullable=True),
    sa.Column('chest_cm', sa.Double(), nullable=True),
    sa.Column('arm_cm', sa.Double(), nullable=True),
    sa.Column('thigh_cm', sa.Double(), nullable=True),
    sa.Column('photo_front_path', sa.String(length=300), nullable=True),
    sa.Column('photo_side_path', sa.String(length=300), nullable=True),
    sa.Column('photo_back_path', sa.String(length=300), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('note IS NULL OR length(note) <= 300', name=op.f('ck_checkins_note_length')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkins_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    sa.UniqueConstraint('user_id', 'week_start', name=op.f('uq_checkins_user_id_week_start'))
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_user_id'), ['user_id'], unique=False)

    op.create_table('exercise_substitutions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.String(length=60), nullable=False),
    sa.Column('substitute_id', sa.String(length=60), nullable=True),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_exercise_substitutions_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['substitute_id'], ['exercises.id'], name=op.f('fk_exercise_substitutions_substitute_id_exercises'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_substitutions'))
    )
    with op.batch_alter_table('exercise_substitutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_substitutions_exercise_id'), ['exercise_id'], unique=False)

    op.create_table('food_grocery_items',
    sa.Column('food_id', sa.String(length=60), nullable=False),
    sa.Column('grocery_item_id', sa.String(length=60), nullable=False),
    sa.Column('raw_grams_per_gram', sa.Double(), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_food_grocery_items_food_id_foods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_items.id'], name=op.f('fk_food_grocery_items_grocery_item_id_grocery_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('food_id', 'grocery_item_id', name=op.f('pk_food_grocery_items'))
    )
    op.create_table('injuries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=6), nullable=False),
    sa.Column('type', sa.String(length=12), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('painful_movements', sa.JSON(), nullable=False),
    sa.Column('restrictions', sa.JSON(), nullable=False),
    sa.Column('since', sa.Date(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('severity BETWEEN 1 AND 5', name=op.f('ck_injuries_severity_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_injuries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_injuries'))
    )
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_injuries_user_id'), ['user_id'], unique=False)

    op.create_table('pantry_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('grocery_item_id', sa.String(length=60), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_items.id'], name=op.f('fk_pantry_items_grocery_item_id_grocery_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pantry_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pantry_items')),
    sa.UniqueConstraint('user_id', 'grocery_item_id', name=op.f('uq_pantry_items_user_id_grocery_item_id'))
    )
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pantry_items_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('trigger', sa.String(length=12), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('maintenance_calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('conservative', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('rules_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('user_id', 'version', name=op.f('uq_plans_user_id_version'))
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_user_id'), ['user_id'], unique=False)

    op.create_table('profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('onboarding_step', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('sex', sa.String(length=6), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height_cm', sa.Double(), nullable=True),
    sa.Column('weight_kg', sa.Double(), nullable=True),
    sa.Column('waist_cm', sa.Double(), nullable=True),
    sa.Column('goal', sa.String(length=20), nullable=True),
    sa.Column('pace', sa.String(length=10), nullable=True),
    sa.Column('experience', sa.String(length=12), nullable=True),
    sa.Column('days_per_week', sa.Integer(), nullable=True),
    sa.Column('session_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('meals_per_day', sa.Integer(), nullable=True),
    sa.Column('cooking_minutes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.JSON(), nullable=False),
    sa.Column('allergies', sa.JSON(), nullable=False),
    sa.Column('fasting', sa.JSON(), nullable=False),
    sa.Column('heart_condition', sa.Boolean(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('pregnancy', sa.Boolean(), nullable=True),
    sa.Column('recent_surgery', sa.Boolean(), nullable=True),
    sa.Column('exercise_medication', sa.Boolean(), nullable=True),
    sa.Column('conservative', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('age IS NULL OR age BETWEEN 18 AND 90', name=op.f('ck_profiles_adult_age')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles'))
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=60), nullable=False),
    sa.Column('food_id', sa.String(length=60), nullable=False),
    sa.Column('grams', sa.Double(), nullable=False),
    sa.Column('amount_en', sa.String(length=80), nullable=False),
    sa.Column('amount_ar', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], name=op.f('fk_recipe_ingredients_food_id_foods')),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_ingredients'))
    )
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_ingredients_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('recipe_steps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.String(length=60), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_ar', sa.Text(), nullable=False),
    sa.Column('timer_sec', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_recipe_steps_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_steps'))
    )
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_steps_recipe_id'), ['recipe_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('weight_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Double(), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("source IN ('daily', 'checkin')", name=op.f('ck_weight_logs_source_values')),
    sa.CheckConstraint('weight_kg BETWEEN 30 AND 300', name=op.f('ck_weight_logs_weight_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weight_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_logs')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_weight_logs_user_id_date'))
    )
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weight_logs_user_id'), ['user_id'], unique=False)

    op.create_table('checkin_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], name=op.f('fk_checkin_answers_checkin_id_checkins'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkin_answers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin_answers')),
    sa.UniqueConstraint('checkin_id', 'question_id', name=op.f('uq_checkin_answers_checkin_id_question_id'))
    )
    with op.batch_alter_table('checkin_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkin_answers_checkin_id'), ['checkin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkin_answers_user_id'), ['user_id'], unique=False)

    op.create_table('meal_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_meal_plans_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plans'))
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plans_user_id'), ['user_id'], unique=False)

    op.create_table('training_programs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=80), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_ar', sa.String(length=120), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('total_weeks', sa.Integer(), nullable=False),
    sa.Column('deload_week', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_training_programs_plan_id_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_training_programs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_programs'))
    )
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_programs_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_programs_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('checkin_id', sa.String(length=36), nullable=True),
    sa.Column('plan_before_id', sa.String(length=36), nullable=True),
    sa.Column('plan_after_id', sa.String(length=36), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('red_flag', sa.Boolean(), nullable=False),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('ai_summary_en', sa.Text(), nullable=True),
    sa.Column('ai_summary_ar', sa.Text(), nullable=True),
    sa.Column('citations', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], name=op.f('fk_weekly_reviews_checkin_id_checkins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_after_id'], ['plans.id'], name=op.f('fk_weekly_reviews_plan_after_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_before_id'], ['plans.id'], name=op.f('fk_weekly_reviews_plan_before_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weekly_reviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weekly_reviews'))
    )
    with op.batch_alter_table('weekly_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_reviews_checkin_id'), ['checkin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('grocery_lists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_plan_id', sa.String(length=36), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('change_note', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('fk_grocery_lists_meal_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grocery_lists_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grocery_lists'))
    )
    with op.batch_alter_table('grocery_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_lists_meal_plan_id'), ['meal_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_lists_user_id'), ['user_id'], unique=False)

    op.create_table('llm_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('weekly_review_id', sa.String(length=36), nullable=True),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Double(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_llm_calls_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_llm_calls_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['weekly_review_id'], ['weekly_reviews.id'], name=op.f('fk_llm_calls_weekly_review_id_weekly_reviews'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_calls'))
    )
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_calls_user_id'), ['user_id'], unique=False)

    op.create_table('meal_plan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('meal_plan_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=10), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('recipe_id', sa.String(length=60), nullable=False),
    sa.Column('portion', sa.Double(), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('fat_g', sa.Integer(), nullable=False),
    sa.Column('eaten', sa.Boolean(), nullable=False),
    sa.Column('replaced_recipe_id', sa.String(length=60), nullable=True),
    sa.Column('reason', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], name=op.f('fk_meal_plan_items_meal_plan_id_meal_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_meal_plan_items_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['replaced_recipe_id'], ['recipes.id'], name=op.f('fk_meal_plan_items_replaced_recipe_id_recipes')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meal_plan_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_plan_items'))
    )
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plan_items_meal_plan_id'), ['meal_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_plan_items_user_id'), ['user_id'], unique=False)

    op.create_table('program_days',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.String(length=3), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_ar', sa.String(length=80), nullable=False),
    sa.Column('est_minutes', sa.Integer(), nullable=False),
    sa.Column('warmup_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.id'], name=op.f('fk_program_days_program_id_training_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_program_days_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_days'))
    )
    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_days_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_days_user_id'), ['user_id'], unique=False)

    op.create_table('grocery_list_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('grocery_list_id', sa.String(length=36), nullable=False),
    sa.Column('grocery_item_id', sa.String(length=60), nullable=False),
    sa.Column('period', sa.String(length=5), nullable=False),
    sa.Column('grams_needed', sa.Double(), nullable=False),
    sa.Column('qty', sa.Double(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('have_it', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grocery_item_id'], ['grocery_items.id'], name=op.f('fk_grocery_list_items_grocery_item_id_grocery_items')),
    sa.ForeignKeyConstraint(['grocery_list_id'], ['grocery_lists.id'], name=op.f('fk_grocery_list_items_grocery_list_id_grocery_lists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_grocery_list_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grocery_list_items'))
    )
    with op.batch_alter_table('grocery_list_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grocery_list_items_grocery_list_id'), ['grocery_list_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grocery_list_items_user_id'), ['user_id'], unique=False)

    op.create_table('program_exercises',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('program_day_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=60), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps', sa.String(length=20), nullable=False),
    sa.Column('rest_sec', sa.Integer(), nullable=False),
    sa.Column('target_rpe', sa.Double(), nullable=False),
    sa.Column('load_factor', sa.Double(), nullable=False),
    sa.Column('weight_step_kg', sa.Double(), nullable=False),
    sa.Column('replaced_exercise_id', sa.String(length=60), nullable=True),
    sa.Column('injury_id', sa.String(length=36), nullable=True),
    sa.Column('swap_kind', sa.String(length=8), nullable=True),
    sa.Column('swap_reason', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_program_exercises_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['injury_id'], ['injuries.id'], name=op.f('fk_program_exercises_injury_id_injuries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], name=op.f('fk_program_exercises_program_day_id_program_days'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_exercise_id'], ['exercises.id'], name=op.f('fk_program_exercises_replaced_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_program_exercises_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_program_exercises'))
    )
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_program_exercises_program_day_id'), ['program_day_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_program_exercises_user_id'), ['user_id'], unique=False)

    op.create_table('workout_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('program_day_id', sa.String(length=36), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_workout_logs_plan_id_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], name=op.f('fk_workout_logs_program_day_id_program_days'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_workout_logs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs'))
    )
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workout_logs_user_id'), ['user_id'], unique=False)

    op.create_table('pain_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('injury_id', sa.String(length=36), nullable=True),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('pain', sa.Integer(), nullable=False),
    sa.Column('sharp_pain', sa.Boolean(), nullable=False),
    sa.Column('swelling', sa.Boolean(), nullable=False),
    sa.Column('numbness', sa.Boolean(), nullable=False),
    sa.Column('worsening', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('workout_log_id', sa.String(length=36), nullable=True),
    sa.Column('checkin_id', sa.String(length=36), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('pain BETWEEN 0 AND 10', name=op.f('ck_pain_logs_pain_range')),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], name=op.f('fk_pain_logs_checkin_id_checkins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['injury_id'], ['injuries.id'], name=op.f('fk_pain_logs_injury_id_injuries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pain_logs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], name=op.f('fk_pain_logs_workout_log_id_workout_logs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pain_logs'))
    )
    with op.batch_alter_table('pain_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pain_logs_injury_id'), ['injury_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pain_logs_user_id'), ['user_id'], unique=False)

    op.create_table('set_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workout_log_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=60), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Double(), nullable=False),
    sa.Column('rpe', sa.Double(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('reps BETWEEN 0 AND 100', name=op.f('ck_set_logs_reps_range')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_set_logs_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_set_logs_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], name=op.f('fk_set_logs_workout_log_id_workout_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_set_logs')),
    sa.UniqueConstraint('workout_log_id', 'exercise_id', 'set_number', name=op.f('uq_set_logs_workout_log_id_exercise_id_set_number'))
    )
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_set_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_set_logs_workout_log_id'), ['workout_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('set_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_set_logs_workout_log_id'))
        batch_op.drop_index(batch_op.f('ix_set_logs_user_id'))

    op.drop_table('set_logs')
    with op.batch_alter_table('pain_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pain_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_pain_logs_injury_id'))

    op.drop_table('pain_logs')
    with op.batch_alter_table('workout_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workout_logs_user_id'))

    op.drop_table('workout_logs')
    with op.batch_alter_table('program_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_exercises_user_id'))
        batch_op.drop_index(batch_op.f('ix_program_exercises_program_day_id'))

    op.drop_table('program_exercises')
    with op.batch_alter_table('grocery_list_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_list_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_grocery_list_items_grocery_list_id'))

    op.drop_table('grocery_list_items')
    with op.batch_alter_table('program_days', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_program_days_user_id'))
        batch_op.drop_index(batch_op.f('ix_program_days_program_id'))

    op.drop_table('program_days')
    with op.batch_alter_table('meal_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plan_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plan_items_meal_plan_id'))

    op.drop_table('meal_plan_items')
    with op.batch_alter_table('llm_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_calls_user_id'))

    op.drop_table('llm_calls')
    with op.batch_alter_table('grocery_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grocery_lists_user_id'))
        batch_op.drop_index(batch_op.f('ix_grocery_lists_meal_plan_id'))

    op.drop_table('grocery_lists')
    with op.batch_alter_table('weekly_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_reviews_checkin_id'))

    op.drop_table('weekly_reviews')
    with op.batch_alter_table('training_programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_programs_user_id'))
        batch_op.drop_index(batch_op.f('ix_training_programs_plan_id'))

    op.drop_table('training_programs')
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_plans_plan_id'))

    op.drop_table('meal_plans')
    with op.batch_alter_table('checkin_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkin_answers_user_id'))
        batch_op.drop_index(batch_op.f('ix_checkin_answers_checkin_id'))

    op.drop_table('checkin_answers')
    with op.batch_alter_table('weight_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weight_logs_user_id'))

    op.drop_table('weight_logs')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('recipe_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_steps_recipe_id'))

    op.drop_table('recipe_steps')
    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_ingredients_recipe_id'))

    op.drop_table('recipe_ingredients')
    op.drop_table('profiles')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_user_id'))

    op.drop_table('plans')
    with op.batch_alter_table('pantry_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pantry_items_user_id'))

    op.drop_table('pantry_items')
    with op.batch_alter_table('injuries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_injuries_user_id'))

    op.drop_table('injuries')
    op.drop_table('food_grocery_items')
    with op.batch_alter_table('exercise_substitutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_substitutions_exercise_id'))

    op.drop_table('exercise_substitutions')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_user_id'))

    op.drop_table('checkins')
    op.drop_table('users')
    op.drop_table('recipes')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_ip'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_email_hash'))

    op.drop_table('login_attempts')
    op.drop_table('grocery_items')
    op.drop_table('foods')
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercises_movement_pattern'))

    op.drop_table('exercises')
    # ### end Alembic commands ###
